[workspace]
members = ["wasm", "core"]
resolver = "2"

[workspace.dependencies]

ssi = "0.12"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

# Wasm dependencies 
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
serde-wasm-bindgen = "0.6"
tracing-wasm = "0.2"


thiserror = "2"
chrono = { version = "0.4", default-features = false, features = [
  "std",
  "clock",
] }

base64 = "0.22"
getrandom = { version = "0.3", features = ["wasm_js"] }

tracing = "0.1"
console_error_panic_hook = "0.1"
tracing-subscriber = "0.3.22"
zeroize = { version = "1.8.2", features = ["zeroize_derive"] }
