# SPDX-FileCopyrightText: 2025 Semiotic AI, Inc.
#
# SPDX-License-Identifier: MIT

[package]
name = "agentium-sdk-core"
version = "0.1.0"
edition = "2024"


[dependencies]
ssi = { workspace = true }

serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }

thiserror = { workspace = true }

chrono = { workspace = true, default-features = false, features = [
  "std",
  "clock",
] }

base64 = { workspace = true }
getrandom = { workspace = true, features = ["wasm_js"] }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }

zeroize = { workspace = true, features = ["zeroize_derive"] }

# EVM signing
alloy-primitives = { workspace = true }
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }
