# SPDX-FileCopyrightText: 2025 Semiotic AI, Inc.
#
# SPDX-License-Identifier: MIT

[package]
name = "agentium-sdk-wasm"
version = "0.1.0"
edition = "2024"
description = "WASM library for Agentium SDK - JWT-VC verification"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ssi = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }

# Wasm dependencies 
wasm-bindgen-futures = { workspace = true }
serde-wasm-bindgen = { workspace = true }
tracing-wasm = { workspace = true }
wasm-bindgen = { workspace = true }


thiserror = { workspace = true }
chrono = { workspace = true, default-features = false, features = [
  "std",
  "clock",
] }

base64 = { workspace = true }
getrandom = { workspace = true, features = ["wasm_js"] }

tracing = { workspace = true }
console_error_panic_hook = { workspace = true }
tracing-subscriber = { workspace = true }
zeroize = { workspace = true, features = ["zeroize_derive"] }


agentium-sdk-core = { path = "../core" }


[dev-dependencies]
wasm-bindgen-test = "0.3.34"
